# Generated by Django 3.1.4 on 2021-01-06 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivereatproj', '0002_auto_20210106_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.date(2021, 1, 6)),
            preserve_default=False,
        ),
    ]
