# Generated by Django 3.1.4 on 2021-01-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivereatproj', '0003_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
